# Generated by Django 3.2.8 on 2021-11-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='userPic/'),
        ),
    ]
