# Generated by Django 3.2.8 on 2021-11-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_userpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPic',
            field=models.ImageField(default=None, upload_to='userPic/'),
        ),
    ]
