# Generated by Django 3.2.8 on 2021-12-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20211228_2223'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='privatechat',
            name='unique chat',
        ),
        migrations.AddConstraint(
            model_name='privatechat',
            constraint=models.UniqueConstraint(fields=('author', 'friend'), name='unique chat1'),
        ),
        migrations.AddConstraint(
            model_name='privatechat',
            constraint=models.UniqueConstraint(fields=('friend', 'author'), name='unique chat2'),
        ),
    ]
