# Generated by Django 3.2.8 on 2021-12-28 17:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20211228_2240'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='privatechat',
            name='unique chat1',
        ),
        migrations.RemoveConstraint(
            model_name='privatechat',
            name='unique chat2',
        ),
        migrations.AlterUniqueTogether(
            name='privatechat',
            unique_together={('author', 'friend')},
        ),
    ]
