# Generated by Django 3.2.8 on 2021-12-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20211228_2248'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='privatechat',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='privatechat',
            constraint=models.UniqueConstraint(fields=('author', 'friend'), name='unique chat'),
        ),
    ]
