# Generated by Django 3.2.8 on 2021-12-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20211229_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='author',
        ),
    ]
