# Generated by Django 3.2.8 on 2021-12-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_groupchat_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechat',
            name='timstamp',
            field=models.DateTimeField(default=None),
        ),
    ]
