# Generated by Django 3.2.8 on 2021-12-31 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_privatechat_timstamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatechat',
            old_name='timstamp',
            new_name='timestamp',
        ),
    ]
